const path = require('path');
const { get2LevelPrefix } = require('../../utils/path');

// Simple, zero-dependency glob to regex converter
function globToRegex(pattern) {
  const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  const regexStr = '^' + escaped
    .replace(/\*\*/g, '__DOUBLE_STAR__')
    .replace(/\*/g, '__SINGLE_STAR__')
    .replace(/\?/g, '__QUESTION__')
    .replace(/__DOUBLE_STAR__/g, '.*')
    .replace(/__SINGLE_STAR__/g, '[^/]*')
    .replace(/__QUESTION__/g, '[^/]')
    + '$';
  return new RegExp(regexStr, 'i');
}

function autogenerateBoundaries(graph, projectContext, workspaceRoot) {
  const prefixes = new Set();
  const fileToPrefix = new Map();
  const mainlineFiles = [];

  // 1. Gather all mainline files and their prefixes
  for (const filePath of graph.getAllFilePaths()) {
    const classification = projectContext?.classifyFile(filePath);
    if (classification && classification.isMainline === true) {
      const relPath = path.relative(workspaceRoot, filePath).replace(/\\/g, '/');
      const prefix = get2LevelPrefix(relPath);
      if (prefix !== '.') {
        prefixes.add(prefix);
        fileToPrefix.set(filePath, prefix);
        mainlineFiles.push(filePath);
      }
    }
  }

  if (prefixes.size < 2) {
    return [];
  }

  // 2. Build directed graph representing directory-level imports
  const edges = new Map(); // prefix -> Set of imported prefixes
  for (const prefix of prefixes) {
    edges.set(prefix, new Set());
  }

  for (const file of mainlineFiles) {
    const sourcePrefix = fileToPrefix.get(file);
    const imports = graph.getDependencies(file) || [];
    for (const target of imports) {
      const targetPrefix = fileToPrefix.get(target);
      if (targetPrefix && targetPrefix !== sourcePrefix) {
        edges.get(sourcePrefix).add(targetPrefix);
      }
    }
  }

  // 3. For any pair of directories A and B where A imports B but B does not import A, suggest: B deny A
  const suggestedRules = [];
  const prefixArray = Array.from(prefixes).sort();
  for (let i = 0; i < prefixArray.length; i++) {
    for (let j = i + 1; j < prefixArray.length; j++) {
      const a = prefixArray[i];
      const b = prefixArray[j];
      const aImportsB = edges.get(a).has(b);
      const bImportsA = edges.get(b).has(a);

      if (aImportsB && !bImportsA) {
        // A imports B, so B is a dependency/lower-level module. B should deny A.
        suggestedRules.push({
          from: `${b}/**`,
          deny: [`${a}/**`]
        });
      } else if (bImportsA && !aImportsB) {
        // B imports A, so A is lower-level. A should deny B.
        suggestedRules.push({
          from: `${a}/**`,
          deny: [`${b}/**`]
        });
      }
    }
  }

  return suggestedRules;
}

function checkBoundaries(args, container) {
  const graph = container.snapshot?.graph || container.depGraph;
  const projectContext = container.projectContext;
  const workspaceRoot = container.workspaceRoot;

  let rules = projectContext?.config?.boundaries || [];
  let isAutogenerated = false;

  if (rules.length === 0) {
    rules = autogenerateBoundaries(graph, projectContext, workspaceRoot);
    isAutogenerated = true;
  }

  const compiledRules = rules.map((r, index) => {
    return {
      original: r,
      index,
      fromRe: globToRegex(r.from),
      denyRe: r.deny ? r.deny.map(globToRegex) : null,
      allowRe: r.allow ? r.allow.map(globToRegex) : null
    };
  });

  const violations = [];

  // Scan all mainline files
  for (const sourceFile of graph.getAllFilePaths()) {
    const sourceClass = projectContext?.classifyFile(sourceFile);
    if (!sourceClass || sourceClass.isMainline !== true) {
      continue;
    }

    const relSource = path.relative(workspaceRoot, sourceFile).replace(/\\/g, '/');

    // Find matching rules
    const matchingRules = compiledRules.filter(cr => cr.fromRe.test(relSource));
    if (matchingRules.length === 0) {
      continue;
    }

    const imports = graph.getDependencies(sourceFile) || [];
    for (const targetFile of imports) {
      const targetClass = projectContext?.classifyFile(targetFile);
      if (!targetClass || targetClass.isMainline !== true) {
        continue;
      }

      const relTarget = path.relative(workspaceRoot, targetFile).replace(/\\/g, '/');

      for (const rule of matchingRules) {
        // 1. Check deny list
        if (rule.denyRe) {
          for (let idx = 0; idx < rule.denyRe.length; idx++) {
            if (rule.denyRe[idx].test(relTarget)) {
              violations.push({
                sourceFile: relSource,
                targetFile: relTarget,
                ruleIndex: rule.index,
                ruleFrom: rule.original.from,
                violationType: 'deny',
                pattern: rule.original.deny[idx]
              });
            }
          }
        }
        // 2. Check allow list
        if (rule.allowRe) {
          let allowed = false;
          for (const re of rule.allowRe) {
            if (re.test(relTarget)) {
              allowed = true;
              break;
            }
          }
          if (!allowed) {
            violations.push({
              sourceFile: relSource,
              targetFile: relTarget,
              ruleIndex: rule.index,
              ruleFrom: rule.original.from,
              violationType: 'allow'
            });
          }
        }
      }
    }
  }

  return {
    ok: true,
    isAutogenerated,
    rulesApplied: rules,
    violationsCount: violations.length,
    violations
  };
}

module.exports = { checkBoundaries };
