/**
 * category-filter.js — shared category filtering utilities
 *
 * Extracted from audit-assembler.js to break a require cycle with
 * incremental-diff.js and to give other curation layers a single,
 * dependency-light source of truth for category filtering.
 */

const { DEFAULTS } = require('../config/constants');

// Category aliases map CLI-friendly names to result section keys.
// Keep in sync with DEFAULTS.FINDING_CATEGORIES and the tools that emit each category.
const CATEGORY_ALIASES = {
  'dead-exports': 'deadExports',
  deadexports: 'deadExports',
  unresolved: 'unresolved',
  cycles: 'cycles',
  boundaries: 'boundaries',
  smells: 'smells',
  health: 'health',
  security: 'security',
  'ast-rules': 'astRules',
  astrules: 'astRules',
};

const EMPTY_CATEGORY_STUBS = {
  deadExports: () => ({
    ok: true,
    deadExportsCount: 0,
    deadExports: [],
    possibleFalsePositives: { count: 0, total: 0, primaryReason: 'unknown', reasons: [], disclaimer: null },
  }),
  unresolved: () => ({ ok: true, unresolvedCount: 0, unresolved: [], possibleFalsePositives: null }),
  cycles: () => ({ ok: true, cyclesCount: 0, cycles: [] }),
  boundaries: () => ({ ok: true, isAutogenerated: false, rulesApplied: [], rulesAppliedCount: 0, violationsCount: 0, violations: [] }),
  smells: () => ({ ok: true, smellsCount: 0, smells: [] }),
  health: () => ({
    ok: true,
    healthScore: '5/5',
    healthScoreNumeric: { passed: 5, total: 5, ratio: 1 },
    checks: {},
  }),
  security: () => ({
    ok: true,
    findings: [],
    summary: { total: 0, bySeverity: { high: 0, medium: 0, low: 0 } },
  }),
  astRules: () => ({ ok: true, findingsCount: 0, findings: [] }),
};

function parseCategories(category) {
  if (!category) return null;
  return String(category)
    .split(',')
    .map((part) => part.trim().toLowerCase())
    .filter(Boolean)
    .map((c) => CATEGORY_ALIASES[c])
    .filter(Boolean);
}

function filterByCategory(result, category, availableKeys) {
  const categories = parseCategories(category);
  if (!categories || categories.length === 0) return result;
  const keep = new Set(categories.filter((c) => availableKeys.includes(c)));
  for (const key of availableKeys) {
    if (!keep.has(key) && result[key] !== undefined) {
      result[key] = EMPTY_CATEGORY_STUBS[key]();
    }
  }
  return result;
}

function validateCategories(category) {
  if (!category) return { valid: true, requested: [], invalid: [] };
  const requested = String(category)
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean);
  const invalid = requested.filter((c) => !DEFAULTS.FINDING_CATEGORIES.has(c.toLowerCase()));
  return { valid: invalid.length === 0, requested, invalid };
}

module.exports = {
  CATEGORY_ALIASES,
  EMPTY_CATEGORY_STUBS,
  parseCategories,
  filterByCategory,
  validateCategories,
};
